---
# -----------------------------------------------------------------------------
# Filename: ansible/roles/dns_adguard/handlers/main.yml
# Created: 2026-01-18
# Description: Handlers for AdGuard Home.
# -----------------------------------------------------------------------------

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart adguardhome
  ansible.builtin.service:
    name: adguardhome
    state: restarted
