---
# -----------------------------------------------------------------------------
# Role: dns_bind9
# Handlers
# -----------------------------------------------------------------------------

- name: Restart bind9
  ansible.builtin.systemd:
    name: bind9
    state: restarted
